from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Asset that we are interested in trading (company ticker or crypto CoinGecko ID)"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media / Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    # Crypto-specific analyst reports
    onchain_report: Annotated[str, "Report from the On-Chain Analyst (blockchain metrics, funding rates, TVL)"]
    prediction_report: Annotated[str, "Report from the Prediction Model Analyst (RF, ARIMA forecasts with confidence intervals)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # Hybrid quant+LLM modulator (Phase 4 / Tier A2 + A5)
    quant_signal: Annotated[
        dict | None,
        "Layer 1 QuantSignal as a dict (model_dump). Populated by the Layer 1 ingestion node before the LLM modulator runs.",
    ]
    factual_report: Annotated[
        str,
        "Factual analyst report (FS-ReasoningAgent split): on-chain + price + derivatives only.",
    ]
    subjective_report: Annotated[
        str,
        "Subjective analyst report: sentiment + news + social only.",
    ]
    regime_reflector_note: Annotated[
        str,
        "Regime-conditional re-weighting note from the Regime Reflector node.",
    ]
    factual_weight: Annotated[float, "Factual lens weight in [0,1]."]
    subjective_weight: Annotated[float, "Subjective lens weight in [0,1]."]
    modulated_position: Annotated[
        dict | None,
        "Layer 2 ModulatedPosition as a dict; emitted by the Modulator node and consumed by Risk debate + PM.",
    ]
    modulator_narrative: Annotated[
        str,
        "Audit-trail narrative emitted by the Modulator (un-masked at boundary).",
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
