#!/usr/bin/env python
"""V5 MIX TP/SL parameter sensitivity sweep.

Iterates a 9 × 6 × 7 grid of (stop_loss, early_exit_loss, take_profit) cells
against the V5 MIX 4-coin equal-weight portfolio over the canonical 4.5-yr
walk-forward window. Caches positions per early_exit_loss value to avoid
redundant position-builder runs (EE drives positions; SL and TP only drive
the engine).

Outputs to data/v5_sltp_sweep/:
  results.csv  — one row per (sl, ee, tp) × scope (portfolio + 4 coins)
  summary.json — grid + V5 baseline reproduction + best cell + git SHA

Reporting (top20.md + heatmaps) is generated by scripts/v5_sltp_sweep_report.py.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.baseline_strategy_v2 import run_coin_backtest  # noqa: E402
from scripts.baseline_v5_mix import (  # noqa: E402
    COSTS, DEFAULT_ROUTING, EARLY_EXIT_DEFAULT, _load_preds, _v2_positions,
)
from tradingagents.dataflows.coingecko_binance import _load_crypto_ohlcv  # noqa: E402

ANN = float(np.sqrt(252))

# Baseline V5 MIX cell — must equal sweep's detection logic + summary.json.
_BASELINE_SL = COSTS["stop_loss"]       # 0.03
_BASELINE_EE = EARLY_EXIT_DEFAULT       # 0.015
_BASELINE_TP = COSTS["take_profit"]     # 0.0

SL_GRID = [0.0, 0.005, 0.01, 0.015, 0.02, 0.03, 0.05, 0.07, 0.10]   # 0.0 = disabled
EE_GRID = [1.0, 0.005, 0.01, 0.015, 0.02, 0.03]                     # 1.0 = effectively disabled (loss > 100%)
TP_GRID = [0.0, 0.01, 0.02, 0.03, 0.05, 0.08, 0.12]                 # 0.0 = disabled

# Smaller grids for smoke
SMOKE_SL = [0.0, 0.03]
SMOKE_EE = [0.015]
SMOKE_TP = [0.0, 0.05]


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=PROJECT_ROOT
        ).decode().strip()
    except Exception:
        return "unknown"


def _metrics(rets: np.ndarray) -> dict:
    """Return a metrics dict for a return series.

    Sign convention (differs from baseline_v5_mix._metrics):
      max_drawdown is a POSITIVE fraction (e.g. 0.049 for a 4.9% peak-to-trough
      drawdown). Calmar uses this positive value as the denominator.
    """
    if len(rets) == 0:
        return dict(sharpe=0.0, total_return=0.0, max_drawdown=0.0,
                    calmar=0.0, win_rate=0.0, profit_factor=0.0, n_bars=0)
    eq = np.cumprod(1.0 + rets)
    sd = float(rets.std(ddof=1)) if len(rets) > 1 else 0.0
    sr = float(rets.mean() / sd * ANN) if sd > 0 else 0.0
    total = float(eq[-1] - 1.0)
    n_yr = len(rets) / 252.0
    ann_ret = (1.0 + total) ** (1.0 / n_yr) - 1.0 if n_yr > 0 else 0.0
    running_max = np.maximum.accumulate(eq)
    dd = float(np.max((running_max - eq) / running_max)) if len(eq) else 0.0
    calmar = float(ann_ret / dd) if dd > 0 else 0.0
    wins = int((rets > 0).sum())
    losses_n = int((rets < 0).sum())
    n_traded = wins + losses_n
    win_rate = float(wins / n_traded) if n_traded > 0 else 0.0
    gp = float(rets[rets > 0].sum())
    gl = float(np.abs(rets[rets < 0].sum()))
    pf = float(gp / gl) if gl > 0 else (float("inf") if gp > 0 else 0.0)
    return dict(
        sharpe=sr, total_return=total, max_drawdown=dd, calmar=calmar,
        win_rate=win_rate, profit_factor=pf, n_bars=int(len(rets)),
    )


def _load_coin_data(coin: str, pred_dir: Path, start: str, end: str) -> pd.DataFrame:
    """Load + merge preds with OHLCV. Same path baseline_v5_mix.run_coin uses."""
    preds = _load_preds(pred_dir, coin)
    preds = preds[(preds["date"] >= start) & (preds["date"] <= end)]
    if preds.empty:
        raise ValueError(f"{coin}: no predictions in [{start}, {end}] under {pred_dir}")
    ohlcv = _load_crypto_ohlcv(coin, end)
    ohlcv["Date"] = pd.to_datetime(ohlcv["Date"]).dt.tz_localize(None).dt.normalize()
    merged = preds.merge(ohlcv[["Date", "Close"]], left_on="date", right_on="Date")
    merged = merged.dropna(subset=["Close"]).reset_index(drop=True)
    merged["ref_price"] = merged["Close"]
    return merged


def _engine_returns(merged: pd.DataFrame, positions: np.ndarray,
                    sl: float, tp: float) -> pd.Series:
    costs = dict(COSTS)
    costs["stop_loss"] = sl
    costs["take_profit"] = tp
    equity, _m = run_coin_backtest(
        dates=merged["date"].values, prices=merged["Close"].values,
        positions=positions, initial_capital=10_000.0, **costs,
    )
    eq = np.asarray(equity, dtype=float)
    rets = eq[1:] / eq[:-1] - 1.0
    return pd.Series(rets, index=pd.to_datetime(merged["date"].values[1:]))


def run_sweep(
    sl_grid: list[float], ee_grid: list[float], tp_grid: list[float],
    start: str, end: str, kelly_fraction: float, out_dir: Path,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    coin_data: dict[str, pd.DataFrame] = {}
    for coin, pdir in DEFAULT_ROUTING.items():
        coin_data[coin] = _load_coin_data(coin, PROJECT_ROOT / pdir, start, end)
    print(f"  Loaded {len(coin_data)} coins in {time.time() - t0:.1f}s")

    rows: list[dict] = []
    n_cells = len(sl_grid) * len(ee_grid) * len(tp_grid)
    cell_i = 0
    baseline_port_sr = None

    # EE is outer axis: positions are EE-dependent (built by _v2_positions),
    # so cache once per EE and reuse across the SL × TP inner sweep.
    for ee in ee_grid:
        # Build positions once per EE (cached across SL × TP inner loop).
        position_cache: dict[str, np.ndarray] = {}
        for coin, merged in coin_data.items():
            position_cache[coin] = _v2_positions(
                merged, kelly_fraction=kelly_fraction, early_exit_loss=ee,
            )
        for sl in sl_grid:
            for tp in tp_grid:
                cell_i += 1
                coin_rets: dict[str, pd.Series] = {}
                for coin, merged in coin_data.items():
                    coin_rets[coin] = _engine_returns(
                        merged, position_cache[coin], sl=sl, tp=tp,
                    )
                df = pd.DataFrame(coin_rets).dropna()
                port = df.mean(axis=1)
                pm = _metrics(port.values)

                rows.append(dict(
                    sl=sl, ee=ee, tp=tp, scope="portfolio", **pm,
                ))
                for coin, r in coin_rets.items():
                    cm = _metrics(r.values)
                    rows.append(dict(
                        sl=sl, ee=ee, tp=tp, scope=coin, **cm,
                    ))

                if sl == _BASELINE_SL and ee == _BASELINE_EE and tp == _BASELINE_TP:
                    baseline_port_sr = pm["sharpe"]

                if cell_i % 20 == 0 or cell_i == n_cells:
                    elapsed = time.time() - t0
                    eta = elapsed / cell_i * (n_cells - cell_i)
                    print(f"  cell {cell_i}/{n_cells}  "
                          f"SL={sl:.3f} EE={ee:.3f} TP={tp:.3f}  "
                          f"port SR={pm['sharpe']:+.2f}  "
                          f"elapsed={elapsed:.0f}s  eta={eta:.0f}s")

    if baseline_port_sr is None:
        print(
            f"  WARNING: baseline cell (SL={_BASELINE_SL}, EE={_BASELINE_EE}, "
            f"TP={_BASELINE_TP}) was NOT in the sweep grid — summary.json "
            f"baseline_cell.portfolio_sharpe will be null.",
            file=sys.stderr,
        )

    df_out = pd.DataFrame(rows)
    df_out.to_csv(out_dir / "results.csv", index=False)

    port_only = df_out[df_out["scope"] == "portfolio"].copy()
    best = port_only.sort_values("sharpe", ascending=False).iloc[0]

    summary = dict(
        grid=dict(sl=sl_grid, ee=ee_grid, tp=tp_grid),
        window=dict(start=start, end=end),
        kelly_fraction=kelly_fraction,
        baseline_cell=dict(sl=_BASELINE_SL, ee=_BASELINE_EE, tp=_BASELINE_TP,
                           portfolio_sharpe=baseline_port_sr),
        best_cell=dict(
            sl=float(best["sl"]), ee=float(best["ee"]), tp=float(best["tp"]),
            portfolio_sharpe=float(best["sharpe"]),
            total_return=float(best["total_return"]),
            max_drawdown=float(best["max_drawdown"]),
            calmar=float(best["calmar"]),
        ),
        n_cells=n_cells,
        wall_clock_sec=time.time() - t0,
        git_sha=_git_sha(),
    )
    with open(out_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)

    print(f"\n  Wrote: {out_dir / 'results.csv'}  ({len(df_out)} rows)")
    print(f"  Wrote: {out_dir / 'summary.json'}")
    if baseline_port_sr is not None:
        print(f"  Baseline cell SR = {baseline_port_sr:+.3f} "
              f"(current canonical V5 MIX = +3.178)")
    print(f"  Best cell: SL={best['sl']} EE={best['ee']} TP={best['tp']}  "
          f"SR={best['sharpe']:+.3f}  DD={best['max_drawdown']:.1%}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--start", default="2021-11-07")
    p.add_argument("--end", default="2026-04-15")
    p.add_argument("--output-dir", default="data/v5_sltp_sweep")
    p.add_argument("--kelly", type=float, default=0.5)
    p.add_argument("--smoke", action="store_true",
                   help="Smoke run on tiny grid (2x1x2=4 cells)")
    p.add_argument("--data-root", default=None)
    args = p.parse_args()

    if args.data_root:
        os.environ["TRADINGAGENTS_DATA_ROOT"] = args.data_root

    if args.smoke:
        sl, ee, tp = SMOKE_SL, SMOKE_EE, SMOKE_TP
        print("  SMOKE MODE — small grid")
    else:
        sl, ee, tp = SL_GRID, EE_GRID, TP_GRID

    out_dir = PROJECT_ROOT / args.output_dir
    print(f"\n  V5 MIX TP/SL sweep")
    print(f"  window : {args.start} → {args.end}")
    print(f"  grid   : SL={len(sl)} EE={len(ee)} TP={len(tp)} = {len(sl) * len(ee) * len(tp)} cells")
    print(f"  output : {out_dir}\n")

    run_sweep(sl, ee, tp, args.start, args.end, args.kelly, out_dir)


if __name__ == "__main__":
    main()
